window.onload=function(){function a(){r=window.innerWidth;l=window.innerHeight;s=new THREE.Clock;o=new THREE.WebGLRenderer({antialias:!1});o.setSize(r,l);o.setClearColorHex(0,1);document.body.appendChild(o.domElement);t=new THREE.Scene;t.fog=new THREE.FogExp2(0,0.0225);t.fog.far=1E4;i=new THREE.Object3D;var a=[["front_left",[-10,0,-10]],["front",[0,0,-10]],["front_right",[10,0,-10]],["front_top_left",[-10,10,-10]],["front_top_right",[-10,10,-10]],["front_down_left",[-10,-10,-10]],["front_down_right",
[-10,-10,-10]],["back",[0,0,10]],["back_left",[-10,0,10]],["back_right",[10,0,10]],["back_top_left",[-10,10,10]],["back_top_right",[10,10,10]],["back_down_left",[-10,-10,10]],["back_down_right",[10,-10,10]],["left",[-10,0,0]],["right",[10,0,0]],["up_left",[-10,10,0]],["up",[0,10,0]],["up_right",[-10,10,0]],["down_left",[-10,-10,0]],["down",[0,-10,0]],["down_right",[10,-10,0]]];i.dummies={};for(var n=0;n<a.length;n++){var q=a[n],h=new THREE.Object3D,x=q[1];h.position.set(x[0],x[1],x[2]);i.add(h);i.dummies[q[0]]=
h}y=new THREE.PerspectiveCamera(60,r/l,1,1E4);y.position=new THREE.Vector3(0,0,0);y.lookAt(z);i.add(y);i.position=new THREE.Vector3(0,100,0);t.add(i);i.lookAt(C);N=document.getElementById("cockpit");K=new CompassDisplay(150,150);N.appendChild(K.domElement);L=new PitchAndRollDisplay(150,150);N.appendChild(L.domElement);Z=new THREE.PointLight(16777215,1,70);i.add(Z);n={buggyDriver:m,worldLength:B};w=buildGurrus(n);t.add(w);w.updateMatrixWorld();t.add(buildGround(n));A=buildRotabugs(n);t.add(A);A.updateMatrixWorld();
O=buildPlancton(n);t.add(O);for(n=0;n<A.children.length;n++)a=A.children[n],a.updateMatrixWorld(),p(a.feet),x=a.feet.geometry.boundingBox,q=Math.abs(x.min.x-x.max.x),h=Math.abs(x.min.y-x.max.y),x=Math.abs(x.min.z-x.max.z),q=new THREE.CubeGeometry(1.05*q,1.05*h,1.05*x),q=new THREE.Mesh(q,new THREE.MeshBasicMaterial({color:16776960,wireframe:!0})),q.position.set(0,0,0),a.add(q),a.collisionMesh=q,q.geometry.computeBoundingBox(),q.visible=!1,D.push(q);for(n=0;n<w.children.length;n++)D.push(w.children[n]),
w.children[n].geometry.computeBoundingBox();document.addEventListener("keydown",d,!1);document.addEventListener("keyup",g,!1);document.addEventListener("mousemove",b,!1);document.addEventListener("mousedown",c,!1);document.addEventListener("mouseup",e,!1);document.addEventListener("contextmenu",function(b){b.preventDefault()},!1);v=new webkitAudioContext;for(n=0;n<$.length;n++)u.push({url:$[n],loaded:!1,loading:!1});f(u[0])}function d(b){switch(b.keyCode){case 38:case 87:I=!0;break;case 40:case 83:J=
!0;break;case 37:case 65:P=!0;break;case 39:case 68:Q=!0;break;case 84:R=!0;break;case 71:S=!0;break;case 70:T=!0;break;case 72:U=!0}}function g(b){switch(b.keyCode){case 38:case 87:I=!1;break;case 40:case 83:J=!1;break;case 37:case 65:P=!1;break;case 39:case 68:Q=!1;break;case 84:R=!1;break;case 71:S=!1;break;case 70:T=!1;break;case 72:U=!1}}function b(b){V=b.pageX-aa;ba=b.pageY-ca;da=!0}function c(b){b.preventDefault();b.stopPropagation();switch(b.button){case 0:I=!0;break;case 2:J=!0}}function e(b){b.preventDefault();
b.stopPropagation();switch(b.button){case 0:I=!1;break;case 2:J=!1}}function f(b){var a=new XMLHttpRequest;a.open("GET",b.url,!0);a.responseType="arraybuffer";a.onload=function(){for(var q=v.createBuffer(a.response,!1),d=b.url,c=0;c<u.length;c++){var e=u[c];if(e.url==d&&!1==e.loaded){e.loaded=!0;e.loading=!1;e.buffer=q;break}}q=!0;for(c=0;c<u.length;c++)if(e=u[c],!e.loaded&&!e.loading){f(e);q=!1;break}W.innerHTML+=".";q&&(X.style.opacity=0,setTimeout(function(){X.style.visibility="hidden";cockpit_wrapper.style.opacity=
1;var b=function(b,c,d){var e=v.createPanner(),n=v.createBufferSource(),d=v.createGainNode();e.setPosition(c.x,c.y,c.z);e.panningModel=1;n.loop=!0;n.buffer=b.buffer;n.connect(e);e.connect(d);e.coneOuterGain=1;e.coneOuterAngle=180;e.coneInnerAngle=0;b.buffer.sampleRate=44100;d.connect(a);n.noteOn(q)},q=v.currentTime+0.02,a,c;a=v.createGainNode();a.gain.value=0.9;v.createDynamicsCompressor?(c=v.createDynamicsCompressor(),c.ratio=2):(c=v.createGainNode(),c.gain.value=1.4);a.connect(c);c.connect(v.destination);
b(u[2],new THREE.Vector3(0,15,0),0.8);b(u[0],new THREE.Vector3(-500,0,500),0.9);b(u[0],new THREE.Vector3(500,0,-500),0.9);b(u[1],new THREE.Vector3(500,0,-500),0.9);b(u[1],new THREE.Vector3(-500,0,500),0.9);var d=4/w.children.length;for(c=0;c<w.children.length;c++){var e=w.children[c].matrixWorld.getPosition().clone();e.y+=2;b(u[4],e,d)}d=2/A.children.length;for(c=0;c<A.children.length;c++)e=A.children[c].matrixWorld.getPosition().clone(),b(u[3],e,d);h();(new TWEEN.Tween(i.position)).to({x:0,y:10,
z:0},25E3).onComplete(function(){Y=false}).easing(TWEEN.Easing.Quadratic.Out).start()},1E3))};a.send()}function p(b){var c={min:new THREE.Vector3,max:new THREE.Vector3},q=b.geometry,b=b.children;q.computeBoundingBox();null!==q.boundingBox&&(c=q.boundingBox);for(var a=0;a<b.length;a++){var e=b[a],d=e.geometry;0<e.children.length?p(e):d.computeBoundingBox();var e=c,h=c.min,i=d.boundingBox.min,f=new THREE.Vector3(0,0,0);f.x=Math.min(h.x,i.x);f.y=Math.min(h.y,i.y);f.z=Math.min(h.z,i.z);e.min=f;e=c;h=
c.max;d=d.boundingBox.max;i=new THREE.Vector3(0,0,0);i.x=Math.max(h.x,d.x);i.y=Math.max(h.y,d.y);i.z=Math.max(h.z,d.z);e.max=i}q.boundingBox=c}function h(){requestAnimationFrame(h);TWEEN.update();var b=s.getDelta(),c=Math.pow(b,2),a=500*c,e=100*c,d=c=0,f=0,g=i.position;if(!Y&&(["x","y","z"].forEach(function(b){var a=j[b];0<Math.abs(a)&&(a-=0<a?e:-e,0.1>=Math.abs(a)&&(a=0),j[b]=a)}),I?j.z-=a:J&&(j.z+=a),U?j.x+=a:T&&(j.x-=a),R?j.y+=a:S&&(j.y-=a),a=i.dummies,c=j.x*b,d=j.y*b,f=j.z*b,0>=j.z?CollisionUtils.collidesMultiple(g,
a.front,[a.front_left,a.front_right,a.front_top_left,a.front_top_right,a.front_down_left,a.front_down_right],f,D)&&(f=0,j.z=0):0<j.z&&CollisionUtils.collidesMultiple(g,a.back,[a.back_left,a.back_right,a.back_top_left,a.back_top_right,a.back_down_left,a.back_down_right],f,D)&&(f=0,j.z=0),0<=j.x?CollisionUtils.collidesMultiple(g,a.right,[a.front_right,a.back_right,a.up_right,a.down_right,a.back_top_right,a.front_top_right,a.back_down_right,a.front_down_right],c,D)&&(c=0,j.x=0):0>j.x&&CollisionUtils.collidesMultiple(g,
a.left,[a.front_left,a.back_left,a.front_top_left,a.front_down_left,a.back_top_left,a.back_down_left],c,D)&&(c=0,j.x=0),0<=j.y?CollisionUtils.collidesMultiple(g,a.up,[a.up_left,a.up_right,a.front_top_right,a.front_top_left,a.back_top_right,a.back_top_left],d,D)&&(d=0,j.y=0):0>j.y&&CollisionUtils.collidesMultiple(g,a.down,[a.down_left,a.down_right,a.front_down_left,a.front_down_right,a.back_down_left,a.back_down_right],d,D)&&(d=0,j.y=0),a=50*b,P?(F-=a,G-=a):Q&&(F+=a,G-=a),a=0.05*b,da))F+=V*a,G+=V*
a,H+=ba*a;H=Math.max(-85,Math.min(85,H));a=(90-H)*Math.PI/180;g=F*Math.PI/180;i.translateX(c);i.translateY(d);i.translateZ(f);i.position.z+E>=B?i.position.z=-B+E:i.position.z-E<=-B&&(i.position.z=B-E);i.position.x+E>=B?i.position.x=-B+E:i.position.x-E<=-B&&(i.position.x=B-E);C.x=i.position.x+100*Math.sin(a)*Math.cos(g);C.y=i.position.y+100*Math.cos(a);C.z=i.position.z+100*Math.sin(a)*Math.sin(g);i.lookAt(C);Y||(i.position.y+=0.02*Math.sin(0.001*Date.now()+0.01*Math.random()),i.position.y-=0.25*b,
i.position.y<ea&&(i.position.y=ea,j.y=0));K.direction=G;L.pitch=-H;K.update();L.update();v.listener.setPosition(i.position.x,i.position.y,i.position.z);v.listener.setVelocity(j.x,j.y,j.z);b=i.up;v.listener.setOrientation(C.x,C.y,C.z,b.x,b.y,b.z);v.listener.speedOfSound=1560-i.position.y;c=1E-4*Date.now();d=5E-4*Date.now();b=0;for(f=A.children.length;b<f;b++){for(var a=A.children[b],g=a.originalVertices,p=a.legs,l=a.feet,r=l.geometry.vertices,m=0;m<g.length;m++){var u=g[m],w=r[m],z=c+m+b;w.x=u.x+0.01*
Math.sin(z);w.z=u.z+0.01*Math.cos(z);w.y=u.y+Math.sin(2*z)}l.geometry.verticesNeedUpdate=!0;p.geometry.verticesNeedUpdate=!0;a.position.y=a.originalPosition.y+0.5*Math.sin(b+d)}c=O.children;b=0;for(d=c.length;b<d;b++)f=c[b],f.rotation.x+=0.01,f.rotation.y+=0.01,f.rotation.z+=0.01,f.position.x+=UTILS.rangeRand(-0.001,0.001),f.position.y+=0.01*Math.random(),300<f.position.y&&(f.position.y=-0.25*Math.random());o.render(t,y)}var m=!1,r,l,o,s,t,y,z=new THREE.Vector3(0,0,-10),Y=!0,B=500,E=25,ea=4,i,C=new THREE.Vector3(0,
0,0),j=new THREE.Vector3(0,0,0);new THREE.Vector3(0,0,0);var G=0,H=0,F=0,I=!1,J=!1,T=!1,U=!1,R=!1,S=!1,P=!1,Q=!1,da=!1,aa=window.innerWidth/2,ca=window.innerHeight/2,V=aa,ba=ca,Z,A,O,w,D=[],N,K,L,v,$=["data/malstrom1-arpeggio.ogg","data/malstrom2-vocoder.ogg","data/nn-xt1-bass.ogg","data/nn-xt2-guitar.ogg","data/subtractor1-beep.ogg"],u=[],W,X;var fa=document.getElementById("container"),ga=document.getElementById("intro"),M=document.getElementById("start");AudioDetector.detects(["webAudioSupport",
"oggSupport"])&&!Detector.webgl?Detector.addGetWebGLMessage({parent:fa}):(fa.style.visibility="hidden",M.addEventListener("click",function n(){M.removeEventListener("click",n);ga.className="loading";M.innerHTML="Please wait while LOADING";W=M;X=document.getElementById("intro_wrapper");setTimeout(a,100)}))};
function CompassDisplay(a,d){var g=document.createElement("canvas"),b=g.getContext("2d"),c=a/2,e=d/2,f=Math.round(d/15);g.width=a;g.height=d;this.direction=0;this.domElement=g;b.font=f+"pt monospace";this.update=function(){b.clearRect(0,0,a,d);b.strokeStyle="#fff";var g=Math.min(c,e),h=0.1*g,g=g-h,m=g-h,r=StringFormat.pad(Math.floor(0<=this.direction?this.direction%360:360+this.direction%360),4,"0");b.fillStyle="#fff";b.fillText(r,c-b.measureText(r).width/2,e+f/2);b.save();b.translate(a/2,d/2);b.rotate(-this.direction*
Math.PI/180);for(var r=0,l=2*Math.PI/32,o=0;32>r;r++,o+=l){var s=Math.sin(o),t=Math.cos(o);b.lineWidth=0==r%4?3:0.5;b.beginPath();b.moveTo(m*s,m*t);b.lineTo(g*s,g*t);b.closePath();b.stroke()}b.fillText("N",-b.measureText("N").width/2,-d/4);b.restore();b.lineWidth=3;b.beginPath();b.moveTo(c,e-f/2-h);b.lineTo(c,h);b.closePath();b.stroke()}}
function PitchAndRollDisplay(a,d){var g=document.createElement("canvas"),b=g.getContext("2d"),c=a/2,e=d/2,f=a/4,p=a/20,h=Math.min(a,d)/10,m=d/20;g.width=a;g.height=d;this.roll=this.pitch=0;this.maximumPitch=90;b.font=m+"pt monospace";b.fillStyle="white";this.update=function(){b.clearRect(0,0,a,d);b.beginPath();b.moveTo(c,e);b.arc(c,e,c-h,0,2*Math.PI,!0);b.clip();b.save();b.translate(c,e+d*this.pitch/this.maximumPitch);b.save();b.rotate(this.roll);b.translate(-c,0);b.fillStyle="rgba(255, 255, 255, 0.2)";
b.beginPath();b.fillRect(0,0,a,d+e);b.fill();b.fillStyle="rgba(255, 255, 255, 0.4)";b.beginPath();b.fillRect(0,-d-e,a,d+e);b.fill();b.restore();b.strokeStyle="#fff";b.lineWidth=1;b.beginPath();b.moveTo(-f,0);b.lineTo(f,0);b.stroke();var g=2*d/30;b.lineWidth=1;for(var l=0;30>=l;l++){var o=-d+l*g,s=p;if(0!=o){if(0==l%5){var s=2*s,t;t=Math.floor(Math.abs(o)/d*this.maximumPitch);b.fillText(t,s+m,o+0.5*m)}b.beginPath();b.moveTo(-s,o);b.lineTo(s,o);b.stroke()}}b.restore();b.lineWidth=3;b.strokeStyle="white";
b.beginPath();b.moveTo(2*h,e);b.lineTo(c-h,e);b.lineTo(c-h,e+h);b.stroke();b.beginPath();b.moveTo(a-2*h,e);b.lineTo(c+h,e);b.lineTo(c+h,e+h);b.stroke()};this.domElement=g}
function buildGurrus(a){for(var d=new THREE.Object3D,g=new THREE.MeshLambertMaterial({color:65280,shading:THREE.FlatShading}),b=0;10>b;b++){for(var c=[],e=[],f=new THREE.Geometry,p=2*Math.PI*b/10,h=150*Math.sin(p),m=150*Math.cos(p),p=45*(1+0.25*Math.sin(2*p)),r=0;20>r;r++){for(k=0;3>k;k++)c.push(new THREE.Vector3(p*(Math.random()-Math.random()),p*(Math.random()-Math.random()),p*(Math.random()-Math.random())));var l=c.length-1;e.push(new THREE.Face3(l-2,l-1,l))}f.vertices=c;f.faces=e;f.computeFaceNormals();
c=new THREE.Mesh(f,g);a.buggyDriver||(c.doubleSided=!0);c.position.set(h,0,m);h=new THREE.MeshLambertMaterial({color:16711680,shading:THREE.FlatShading});m=new THREE.Geometry;e=[];f=[];e.push(new THREE.Vector3(-10,0,0));e.push(new THREE.Vector3(10,0,0));e.push(new THREE.Vector3(0,10,0));f.push(new THREE.Face3(0,1,2));m.vertices=e;m.faces=f;m.computeFaceNormals();h=new THREE.Mesh(m,h);a.buggyDriver||(h.doubleSided=!0);h.position.set(0,0,0);h.rotation.set(Math.random(),Math.random(),Math.random());
c.add(h);d.add(c)}return d}
function buildGround(a){for(var d=a.worldLength||500,g=2*d,b=2*d,d=-0.5*g,c=-0.5*b,g=g/300,e=b/300,f,p,h,m,r,l,o,s,b=[],t=[],y=h=p=f=0;300>y;y++){r=h;h=c+y*e;for(var z=0;300>z;z++)py0=p,p=Math.random(0,4),m=f,f=d+z*g,0<z&&0<y&&(b.push(new THREE.Vector3(m,1.5*Math.random(),r)),b.push(new THREE.Vector3(m,1.5*Math.random(),h)),b.push(new THREE.Vector3(f,1.5*Math.random(),r)),s=b.length-1,o=s-1,l=o-1,l=new THREE.Face3(l,o,s),t.push(l),b.push(new THREE.Vector3(m,1.5*Math.random(),h)),b.push(new THREE.Vector3(f,
1.5*Math.random(),h)),b.push(new THREE.Vector3(f,1.5*Math.random(),r)),s=b.length-1,o=s-1,l=o-1,l=new THREE.Face3(l,o,s),t.push(l))}d=new THREE.Geometry;d.vertices=b;d.faces=t;d.computeFaceNormals();c=new THREE.MeshLambertMaterial({color:65280,shading:THREE.FlatShading});d=new THREE.Mesh(d,c);a.buggyDriver||(d.doubleSided=!0);return d}
function buildRotabugs(){for(var a=new THREE.Object3D,d=new THREE.LineBasicMaterial({color:65280,linewidth:1}),g=new THREE.ParticleBasicMaterial({color:65280,size:0.25}),b=0;10>b;b++){for(var c=new THREE.Object3D,e=[],f=new THREE.Geometry,p=[],h=new THREE.Geometry,m=[],r=5*Math.random()+1,l=new THREE.SphereGeometry(r,10,10),r=new THREE.Vector3(0,0,0),l=l.vertices,o=0;o<l.length;o++){var s=l[o];e.push(r);e.push(s);p.push(s);m.push(s.clone())}f.vertices=e;f.computeVertexNormals();f.computeBoundingSphere();
e=new THREE.Line(f,d);c.add(e);h.vertices=p;p=new THREE.ParticleSystem(h,g);c.add(p);c.originalVertices=m;c.legs=e;c.feet=p;c.position.x=70*(Math.random()-Math.random());c.position.y=5;c.position.z=70*(Math.random()-Math.random());c.originalPosition=new THREE.Vector3(c.position.x,c.position.y,c.position.z);a.add(c)}return a}
function buildPlancton(a){for(var d=new THREE.Object3D,g=new THREE.MeshLambertMaterial({color:65280,shading:THREE.FlatShading}),b=0;2E3>b;b++){var c=[],e=[],f=new THREE.Geometry,p=0.1+0.4*Math.random();c.push(new THREE.Vector3(0,0,0));c.push(new THREE.Vector3(p,0,0));c.push(new THREE.Vector3(0,p,0));e.push(new THREE.Face3(0,1,2));f.vertices=c;f.faces=e;f.computeFaceNormals();c=new THREE.Mesh(f,g);c.position.x=UTILS.rangeRand(-100,100);c.position.y=UTILS.rangeRand(-100,100);c.position.z=UTILS.rangeRand(-100,
100);c.rotation.x=UTILS.rangeRand(-100,100);c.rotation.y=UTILS.rangeRand(-100,100);c.rotation.z=UTILS.rangeRand(-100,100);a.buggyDriver||(c.doubleSided=!0);d.add(c)}return d}
var CollisionUtils={collides:function(a,d,g,b,c,e){d.matrixWorld.getPosition().clone();g=g.matrixWorld.getPosition().clone();b=b.matrixWorld.getPosition().clone();d=this.getDirectionVector(a,d);a=new THREE.Ray(g,d);g=new THREE.Ray(b,d);d=[];a=a.intersectObjects(e);e=g.intersectObjects(e);0==a.length&&0<e.length?d=e:0==e.length&&0<a.length?d=a:0<a.length&&0<e.length&&(d=a[0].distance>e[0].distance?e:a);return 0<d.length&&d[0].distance<=Math.abs(c)?!0:!1},collidesMultiple:function(a,d,g,b,c){d.matrixWorld.getPosition().clone();
a=this.getDirectionVector(a,d);for(d=0;d<g.length;d++){var e=g[d].matrixWorld.getPosition().clone(),e=(new THREE.Ray(e,a)).intersectObjects(c);if(void 0!==e&&0<e.length&&e[0].distance<=Math.abs(b))return!0}return!1},getDirectionVector:function(a,d){return d.matrixWorld.getPosition().clone().subSelf(a).normalize()}},StringFormat={pad:function(a,d,g){var b=0<=a?1:-1,a=Math.abs(a).toString();for(0>b&&d--;a.length<d;)a=g+a;0>b&&(a="-"+a);return a},toFixed:function(a){return Math.floor(100*a)/100}};
UTILS={getAxis:function(a){for(var a=a||1E3,a=[{points:[[0,0,0],[a,0,0]],color:16711680},{points:[[0,0,0],[-a,0,0]],color:8388608},{points:[[0,0,0],[0,a,0]],color:65280},{points:[[0,0,0],[0,-a,0]],color:32768},{points:[[0,0,0],[0,0,a]],color:255},{points:[[0,0,0],[0,0,-a]],color:128}],d=new THREE.Object3D,g=0;g<a.length;g++){for(var b=a[g],c=new THREE.Geometry,e=0;e<b.points.length;e++){var f=b.points[e];c.vertices.push(new THREE.Vector3(f[0],f[1],f[2]))}b=new THREE.LineBasicMaterial({color:b.color,
linewidth:2});c=new THREE.Line(c,b);c.position.x=0;c.position.y=0;c.position.z=0;d.add(c)}return d},rangeRand:function(a,d){a=a||-1;return a+Math.random()*((d||1)-a)}};
